ALTER TABLE emails ADD COLUMN IF NOT EXISTS is_critical   BOOLEAN    DEFAULT FALSE;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS summary       TEXT;
ALTER TABLE emails ADD COLUMN IF NOT EXISTS actioned_at   TIMESTAMPTZ;
